Adding Unity support for Airsim. Windows only for now.
microsoft/AirSim pull request #1453
Opened 2018-10-11 00:14 UTC by kenbier

## TODO
- [ ] Replace zipped drone with compressed version
- [ ] Add build docs
- [ ] Add to build.cmd to build AirLibWrapper
- [ ] UnityDistanceSensor::getRayLength() - Need this info from Unity using pinvoke
- [ ] CarPawnApi::getCarState() - GetEngineRotationSpeed, GetEngineMaxRotationSpeed need to be implemented
- [ ] CarPawnApi::reset() - and few more places need to evaluate option of using threads for better performance.
- [ ] Convert_to_AirsimResponse() - Need to get camera_name from source. Currently it crashes when there is a string in structure used for data transfer in PInvoke.
- [ ]  Replace own `Logger.cpp` with `apache's Log4Cxx`
- [ ] Remove any dead code

2018-10-11 00:14 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Microsoft/AirSim?pullRequest=1453) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Microsoft/AirSim?pullRequest=1453) before we can accept your contribution.<br/><br/>:x: kenbier [sign now](https://cla.opensource.microsoft.com/Microsoft/AirSim?pullRequest=1453)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Microsoft/AirSim?pullRequest=1453) it.</sub>

2018-10-15 13:07 UTC, ankitdubeyryt commented
> 
> ## TODO
> 
>     * [x]  Replace zipped drone with compressed version (currently over 100 MB)
> 
>     * [ ]  Add build docs
> 
>     * [ ]  Add to build.cmd to build AirLibWrapper
> 
>     * [ ]  UnityDistanceSensor::getRayLength() - Need this info from Unity using pinvoke
> 
>     * [X]  CarPawnApi::getCarState() - GetEngineRotationSpeed, GetEngineMaxRotationSpeed need to be implemented
> 
>     * [X]  CarPawnApi::reset() - and few more places need to evaluate option of using threads for better performance.
> 
>     * [ ]  Convert_to_AirsimResponse() - Need to get camera_name from source. Currently it crashes when there is a string in structure used for data transfer in PInvoke.
> 
>     * [ ]   Replace own `Logger.cpp` with `apache's Log4Cxx`
> 
>     * [X]  Remove any dead code
>     * [ ] Add check for missing `Settings.json` file.

2018-10-16 23:03 UTC, sytelus requested changes
These changes are not needed?

2018-10-16 23:12 UTC, sytelus requested changes
The drone.obj is very large file in the repo. Can we reduce its size as we discussed? If you have high resolution assets, we can add that separately as zip file in Releases section.

If you can update the README with build and usage instructions, I can start testing on my machine.

2018-10-16 23:12 UTC, sytelus commented on AirLib/AirLib.vcxproj
>        <PreprocessorDefinitions>_SCL_SECURE_NO_WARNINGS;_CRT_SECURE_NO_WARNINGS;_DEBUG;_LIB;%(PreprocessorDefinitions)</PreprocessorDefinitions>
Changes in this file doesn't seem to be needed

2018-10-16 23:12 UTC, sytelus commented on AirLib/include/vehicles/multirotor/firmwares/simple_flight/firmware/Params.hpp
> -        const float kMaxLimit = 6.0f; // m/s
Please remove unnecessary changes in this file.

2018-10-16 23:12 UTC, sytelus commented on setup.sh
> -    brew install coreutils
Could you please explain why this is commented?

2018-10-16 23:12 UTC, sytelus commented on Unity/DroneDemo/README.md
> +
Could have Build section that specifies steps for creating the build? We should start with where and which version of Unity to install.

2018-10-16 23:12 UTC, sytelus commented on Unity/DroneDemo/README.md
> +    WASD\Arrow keys: Drone movement.
If you are using AirLib then drone can only be flown using RC. Is there any additional code in Unity port to enable these keys?

2018-10-17 20:03 UTC, kenbier commented on setup.sh
> -    brew install coreutils
Mistaken commit. I will remove

2018-10-18 05:15 UTC, kenbier commented
@shital I removed the drone file and undid the changes to the AirLib directory. 
Docs coming next

2018-10-18 23:51 UTC, kenbier commented
docs are added. I will wait on squashing until the TODO's are finished.

2018-10-18 23:51 UTC, kenbier commented on Unity/DroneDemo/README.md
> +
done

2018-11-03 00:12 UTC, kenbier commented
@sytelus, won't you mind reverting the merge of this branch into master? We have done a rebase to get rid of large objects from the git history

2018-11-08 22:23 UTC, merged