Make WindowsTargetPlatformVersion more easily configurable in AirSim
microsoft/AirSim pull request #1613
Opened 2018-12-07 20:37 UTC by lovettchris

This change adds a shared MSBuild file called AirSim.props so that it is easier to change the WindowsTargetPlatformVersion in your AirSim build.  This makes it easier for folks to build AirSim using Windows 10 SDK, since installing the Windows 8.1 SDK is a bit of a pain these days.

2018-12-10 06:08 UTC, sytelus requested changes

2018-12-10 06:08 UTC, sytelus commented on AirLib/AirLib.vcxproj
> +  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), AirSim.props))\AirSim.props" />
How does this affect experience from building and using IDE? For example, can I still override this option from IDE or do I must use new prop file?

2018-12-10 06:08 UTC, sytelus commented on AirSim.sln
> +		{9FE9234B-373A-4D5A-AD6B-FB0B593312DD}.Debug|ARM.ActiveCfg = Debug|Win32
Curious if Win32 and Arm build is actually working...

2018-12-10 06:08 UTC, sytelus commented on DroneServer/log
> +Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
Do we need this file?

2018-12-10 06:08 UTC, sytelus commented on build.cmd
> +copy /y AirSim.props Unreal\Plugins\AirSim\Source\AirLib
Would it be better to just mark .prop file as Copy if newer for build output?

2018-12-12 04:40 UTC, clovett commented on AirLib/AirLib.vcxproj
> +  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), AirSim.props))\AirSim.props" />
VS IDE build is the same, and it would be best to change the AirSim.props instead of manually changing every VS project to the new version you want.  Note that after changing AirSim.props you may need to restart VS in order to force this new version to be loaded.  If you edit the projects directly it would probably undo the change I'm making here by adding <WindowsTargetPlatformVersion>…</…> back to all the .vcxproj files, which kind of defeats the point of this change.

2018-12-12 04:40 UTC, clovett commented on AirSim.sln
> +		{9FE9234B-373A-4D5A-AD6B-FB0B593312DD}.Debug|ARM.ActiveCfg = Debug|Win32
VS did this, not me.  Not sure why.

2018-12-12 04:43 UTC, lovettchris commented on DroneServer/log
> +Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
removed

2018-12-12 04:45 UTC, lovettchris commented on build.cmd
> +copy /y AirSim.props Unreal\Plugins\AirSim\Source\AirLib
that would copy build output, this is copying sources.  But I could add a special msbuild copy instruction to copy the file to .\AirLib so it gets picked up by the robocopy.  but then people would check it in.  So I think this is better for now.

2018-12-12 04:47 UTC, lovettchris commented on AirLib/AirLib.vcxproj
> +  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), AirSim.props))\AirSim.props" />
github swallowed my take name, editing the project properties would add the WindowsTargetPlatformVersion tag back to the .vcxproj files, which is not what you want.

2018-12-12 04:48 UTC, lovettchris commented on AirLib/AirLib.vcxproj
> +  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), AirSim.props))\AirSim.props" />
it might be possible to add a new MSBuild rule also to the AirSim.props to check for that and educate the user on the right way to modify this property.

2018-12-14 18:55 UTC, merged