Gui for settings file selection
microsoft/AirSim pull request #1713
Opened 2019-01-17 00:25 UTC by msb336

This pr adds a gui that shows a dropdown menu of all json files in the Documents/AirSim directory.
[demo](https://youtu.be/oFCB2wC9vjY)

2019-01-17 23:01 UTC, jasonhbartlett commented
This is pretty cool.  Should be pretty easy to implement in Unity as well.

2019-04-09 21:09 UTC, madratman reviewed
It works OTB, added comments. most are just formatting comments. 
The main thing to check is if  buildScene() can be called in beginplay and wait to continue till user input is received?

2019-04-09 21:09 UTC, madratman commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.h
>  UENUM(BlueprintType)
we should remove all extraneous empty lines added

2019-04-09 21:09 UTC, madratman commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.h
> +    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Settings Widget")
rename uproperty to Settings Widget Loader to avoid conflict with the settings widget below

2019-04-09 21:09 UTC, madratman commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
> +        not_built_ = false;
instead of calling buildScene() in tick() and checking if not_built_ is false in every subsequent tick, why not call it  in void ASimHUD::BeginPlay()? 
Does that crash unreal?

2019-04-09 21:21 UTC, madratman commented on Unreal/Plugins/AirSim/Source/SimHUD/SettingsWidget.h
> +#ifdef _WIN32
we can remove this ifdef clause

2019-04-09 21:22 UTC, madratman commented on Unreal/Plugins/AirSim/Source/SimHUD/SettingsWidget.h
> +// Fill out your copyright notice in the Description page of Project Settings.
is this needed or from some boilerplate?

2019-04-09 21:23 UTC, madratman reviewed
minor update in review

2019-04-09 22:07 UTC, madratman commented on Unreal/Plugins/AirSim/Source/SimHUD/dirent.h
> +
#include<windows.h> is problematic for linux ofc
Interestingly, I updated the PR branch some changes and now on compiling the second time, include<windows.h> is throwing an error. 
I am not sure why it compiled on the first try in ubuntu 16.04

2019-04-09 22:49 UTC, madratman commented
changes needed were pretty minor, and I overlayed a commit over Matt's awesome work. 
@sytelus this is ready for a merge.

2019-04-10 01:51 UTC, madratman commented
force pushed to fix commit authors

2019-04-10 03:18 UTC, sytelus requested changes

2019-04-10 03:18 UTC, sytelus commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
> +        not_built_ = false;
Agreed. We need to avoid more code in tick().

2019-04-10 03:18 UTC, sytelus commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
> +void ASimHUD::buildScene()
HUD is not supposed to create scene so buildScene name is confusing.  May be createWidgets or initialize or something like that?

2019-04-10 03:18 UTC, sytelus commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
> +        AirSimSettings::createDefaultSettingsFile("settings_default.json"); // do not overwrite user's settings.json!
What is going on here? We don't create settings.json? Please write comment if there is a major change from how things worked previously.

2019-04-10 03:18 UTC, sytelus commented on Unreal/Plugins/AirSim/Source/SimHUD/dirent.h
> +/*
What is this file and why is it needed?

2019-04-10 03:36 UTC, madratman commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
> +        AirSimSettings::createDefaultSettingsFile("settings_default.json"); // do not overwrite user's settings.json!
so the widget has an option to select the default settings.json, which calls AirSimSettings::createDefaultSettingsFile(), which (over)writes the user's settings.json in this line https://github.com/Microsoft/AirSim/blob/85fe8d4987339d5f32f1cf8ffc56b9f64636f789/AirLib/include/common/AirSimSettings.hpp#L406 in the current master branch. 

I think a lot of our users would have a custom file at their /home/$USER/Documents/AirSim/settings.json, and the widget should NOT overwrite that. 

Therefore, I added a default parameter for the local filename in this line https://github.com/Microsoft/AirSim/pull/1713/files#diff-4ee334619d0e207657a29f2139412385R396 to not overwrite settings.json, but instead create a settings_default.json. 

uh, while I am typing this, I do realize that perhaps I should just have defined another function / added a boolean parameter to createDefaultSettingsFile which would simply by pass the saveJsonFile() command https://github.com/Microsoft/AirSim/blob/85fe8d4987339d5f32f1cf8ffc56b9f64636f789/AirLib/include/common/AirSimSettings.hpp

lemme know what you think is better.

2019-04-11 19:51 UTC, msb336 commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
> +        not_built_ = false;
If placed in BeginPlay the widget does not continue to check for user input after BeginPlay is called

2019-04-13 00:49 UTC, sytelus requested changes

2019-04-13 00:49 UTC, sytelus commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
> +        AirSimSettings::createDefaultSettingsFile("settings_default.json"); // do not overwrite user's settings.json!
Either way it would work. I'm just trying to understand workflow... I'm hoping user has option to modify json whichever they like. So they may modify using notepad or using UX. For example, I might modify in Notepad, save it and then reload it in UX and modify again. Would this work? Also, does default settings.json gets created on startup (if it doesn't exist)?

2019-04-13 00:49 UTC, sytelus commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
> +        not_built_ = false;
That doesn't sound right. Widget shouldn't need to be in game loop. That would be no-go scenario. Typical game might have dozens of complex widgets and if all of them need to be ticked all the time, it won't fly. This widget won't be shown 99.99% of the time but would get ticked all the time.

2019-04-13 00:49 UTC, sytelus commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
+1 this is important and often causes issue on Linux because git converts CRLF on fly.

2019-04-13 01:33 UTC, msb336 commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
> +        AirSimSettings::createDefaultSettingsFile("settings_default.json"); // do not overwrite user's settings.json!
The only json creation is when the default (empty) settings is selected. Otherwise, the widget only produces a dropdown menu of json files located in the Documents/AirSim directory.
[demo here](https://studio.youtube.com/video/oFCB2wC9vjY)

2019-04-13 02:09 UTC, madratman commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp
Haha, I end up always using git in WSL when working in windows. Anyway, this should be resolved.. I think I fixed that in my commit.
In general, we do have a mix of tabs and spaces in airsim code https://youtu.be/SsoOG6ZeyUI

2019-05-14 23:30 UTC, closed without merging