Sensors from JSON and more
microsoft/AirSim pull request #2821
Opened 2020-07-01 06:41 UTC by ACLeighner

Proposing a few changes here:
-Added ability to load parameters for JSON for Barometer, Distance Sensor, IMU, GPS, Magnetometer
-Small change to python types doc, fixes a change I proposed before with better datatypes (float vs quaternion) for distance sensor
-Small change to documentation on linux build, sometimes deleting the 'binaries' and 'intermediate' folders in your unreal project after rebuilding airsim can fix errors where unreal tries to open content that doesnt exist anymore and causes the 'try rebuilding from source' error
-small change to move on path, replaces the position PID to use the velocity PID when traveling at constant altitude, elimnates shake problems
 

TODO: 
-did not update documentation to show the new fields available for settings...

2020-07-01 10:25 UTC, rajat2004 reviewed
Great PR! Adding settings for all the sensors will be a great addition. Just a few comments -

- Would be great if the indentation would be consistent, tabs and spaces are intermixed, will be better to use 4 spaces throughout
- There's an open PR #2807 which exposes the settings for Distance sensor, along with adding an option for drawing debug point like Lidar. It might be better to do all the Distance sensor changes in that PR since will make it easier to review and avoid merge conflicts

2020-07-01 10:25 UTC, rajat2004 commented on Unreal/Plugins/AirSim/AirSim.uplugin
> +  "VersionName": "1.2.0",
Probably unintentional change, should be reversed

2020-07-01 10:25 UTC, rajat2004 commented on docs/build_linux.md
Maybe add a line here regarding [`clean.sh`](https://github.com/microsoft/AirSim/blob/master/Unreal/Environments/Blocks/clean.sh) which does all this

2020-07-01 10:25 UTC, rajat2004 commented on AirLib/include/sensors/imu/ImuSimpleParams.hpp
> +    Pose relative_pose;
I don't see this being used anywhere?

2020-07-01 10:25 UTC, rajat2004 commented on AirLib/include/sensors/gps/GpsSimpleParams.hpp
> +    Pose relative_pose;
Unused

2020-07-01 10:29 UTC, rajat2004 commented
Also, I'm not very sure about exposing each setting of the sensors such as noise, but if a user is modifying those, then they probably know what they're doing, so shouldn't be a problem. Though some explanation for all of them will need to be added

2020-07-24 07:02 UTC, madratman requested changes

2020-07-24 07:02 UTC, madratman commented on PythonClient/airsim/types.py
> +    max_distance = np.float32(0)
this can be removed as https://github.com/microsoft/AirSim/pull/2807 is in

2020-07-24 07:02 UTC, madratman commented on AirLib/src/vehicles/multirotor/api/MultirotorApiBase.cpp
> +        moveByVelocityInternal(velocity_vect.x(), velocity_vect.y(), 0, yaw_mode);
can you move the moveOnPath changes to a separate PR? 
Can you share a test script to showcase this fixed the shaking issue?

2020-07-24 07:02 UTC, madratman commented on Unreal/Plugins/AirSim/AirSim.uplugin
> +  "VersionName": "1.2.0",
agreed

2020-07-24 07:02 UTC, madratman commented on PythonClient/multirotor/path.py
> +client.moveToZAsync(z, 5).join()
why is this change needed, can you please justify it? 
seems like a leftover from your testing?

2020-07-24 07:02 UTC, madratman commented
Also conflicts need to be resolved.

2021-02-09 18:20 UTC, rajat2004 commented
@ACLeighner This branch now contains commits not related to the PR, cause its made from the master branch. It'll be best to create a new PR from the original commits using a separate branch if still interested in getting this feature in

2021-02-24 17:46 UTC, jonyMarino commented
Hi @ACLeighner! Thanks for your contribution! I think it is time to merge it. Can you rebase your PR and solve the conflicts? Thanks!

2021-05-19 20:24 UTC, evroon commented
This issue can be closed, its features have already been merged into master with commit 006d4e2.

2021-05-26 20:27 UTC, jonyMarino commented
Thanks, @evroon for highlighting it

2021-05-26 20:27 UTC, closed without merging