Voxel grid construction
microsoft/AirSim pull request #3209
Opened 2020-12-12 02:51 UTC by saihv

### About
This PR introduces a feature that constructs ground truth voxel grids of the world directly from Unreal Engine. The voxel grids are stored in a [binvox format](https://www.patrickmin.com/binvox/binvox.html) which can then be converted by the user into an octomap .bt or any other relevant, desired format. Subsequently, these voxel grids/octomaps can be used within mapping/planning.

The logic for constructing the voxel grid is in WorldSimApi.cpp->createVoxelGrid(). For now, the assumption is that the voxel grid is a cube - and the API call is:

```
createVoxelGrid(self, position, x, y, z, res, of)

position (Vector3r): Global position around which voxel grid is centered in m
x, y, z (float): Size of each voxel grid dimension in m
res (float): Resolution of voxel grid in m
of (str): Name of output file to save voxel grid as
```

### How Has This Been Tested?
Simple test script:
```
import airsim
c = airsim.VehicleClient()
center = a.Vector3r(0, 0, 0)
c.createVoxelGrid(center, 100, 100, 100, 0.5, "map.binvox")
```

[viewvox](https://www.patrickmin.com/viewvox/) is a nifty little utility to then visualize the created binvox file. Similarly, `binvox2bt` can convert the binvox to an octomap file.

### Example voxel grid in Blocks:
![image](https://user-images.githubusercontent.com/2274262/101970694-c7755280-3be0-11eb-886c-74f05c839478.png)

2020-12-12 06:20 UTC, rajat2004 reviewed
Wow, looks pretty awesome

2020-12-12 06:20 UTC, rajat2004 commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +    voxel_grid_.resize(ncells_x * ncells_y * ncells_z);
`voxel_grid_` doesn't seem to have been declared anywhere

2020-12-12 06:20 UTC, rajat2004 commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +    std::ofstream* output = new std::ofstream(output_file, std::ios::out | std::ios::binary);
I think we can just do `std::ofstream output(output_file, std::ios::out | std::ios::binary)` and use the object later on directly, no need to `new` and dereference and all, also not sure but `new` can give memory leaks if not deleted in this case

2020-12-12 07:59 UTC, saihv commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +    voxel_grid_.resize(ncells_x * ncells_y * ncells_z);
Whoops, not sure how that line went missing from the commit. Fixed

2020-12-12 07:59 UTC, saihv commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +    std::ofstream* output = new std::ofstream(output_file, std::ios::out | std::ios::binary);
You're right, safer this way too. Fixed

2020-12-12 08:02 UTC, saihv commented
@jonyMarino @zimmy87 Any ideas why the azure CI pipelines are not getting triggered for PRs?

2020-12-12 10:45 UTC, rajat2004 commented
Yup, fixing the CI would be a big help, there's an open PR to add Gtihub Actions also, to replace Travis - https://github.com/microsoft/AirSim/pull/3180

2020-12-13 12:08 UTC, rajat2004 commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +        std::cerr << "Error: Could not open output file " << &output << "!" << std::endl;
Shouldn't it be `output_file` here, right now it would just print a memory address

2020-12-13 12:10 UTC, rajat2004 commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +        exit(1);
Shouldn't it be `output_file` above in the error message, right now it would just print a memory address
Also, just a thought, do we want to exit if it fails to open the file, or just return `false`?

2020-12-14 21:39 UTC, saihv commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +        exit(1);
Good catch - that was a copy paste artifact I forgot to fix :-) 

I modified the function to return the status, and also display a UE message instead if the file cannot be opened.

2020-12-15 04:35 UTC, rajat2004 reviewed
Just some small nitpicks

2020-12-15 04:35 UTC, rajat2004 commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +    int ctr = 0;
Unused variable

2020-12-15 04:35 UTC, rajat2004 commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +    output << "translate " << int(-x_size/2) << " " << int(-y_size / 2) << " " << int(-z_size/2) << "\n";
`x_size` and others are integers, so casting shouldn't be required here

2020-12-15 04:35 UTC, rajat2004 commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +    output << "scale " << 1/x_size << "\n";
`x_size` is an integer here, so the output will always be 0 for `x_size > 1`, maybe it was meant to be `1.0f/x_size`

2020-12-15 07:52 UTC, saihv commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +    output << "translate " << int(-x_size/2) << " " << int(-y_size / 2) << " " << int(-z_size/2) << "\n";
Fixed

2020-12-15 07:52 UTC, saihv commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +    output << "scale " << 1/x_size << "\n";
Fixed. This was a weird parameter, according to the binvox documentation, scale is important to tell how much to scale the grid by to fit in a 1x1x1 unit cube, but viewvox displays the voxel grid regardless of what value. Probably should keep an eye on this.

2020-12-15 12:54 UTC, rajat2004 commented
Seems like Azure Pipelines is active now, from the [latest commit checks](https://github.com/microsoft/AirSim/runs/1553617586)
Though Windows build has failed

2020-12-15 18:36 UTC, saihv commented
It's the Windows container initialization that's failing during CI.

@jonyMarino Just a heads up
```
2020-12-14T22:53:40.8901202Z 
##[section]Starting: Initialize containers
2020-12-14T22:53:41.0464982Z 
##[command]C:\Program Files\Docker\docker.EXE version --format '{{.Server.APIVersion}}'
2020-12-14T22:53:42.6313274Z error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
2020-12-14T22:53:42.6315842Z '
2020-12-14T22:53:42.8171413Z 
##[error]Exit code 1 returned from process: file name 'C:\Program Files\Docker\docker.EXE', arguments 'version --format '{{.Server.APIVersion}}''.
2020-12-14T22:53:42.8190394Z 
##[section]Finishing: Initialize containers
```

2020-12-15 22:17 UTC, jonyMarino commented
Hi @saihv, I do not know if you get a report with the CI results.

2020-12-15 22:41 UTC, saihv commented
@jonyMarino Thanks for re-enabling CI - will fix the Unity build shortly.

2020-12-16 14:38 UTC, jonyMarino commented
Thank @rajat2004. This came from his work with GitHub Actions (#3180). We still see what happens with Azure pipelines.

2020-12-16 18:46 UTC, zimmy87 requested changes
Tested this locally and it works for me. Only comment is function naming-related.

2020-12-16 19:27 UTC, saihv commented on PythonClient/airsim/client.py
> +    def createVoxelGrid(self, position, x, y, z, res, of):
You're right. Fixed, thanks for the catch

2020-12-16 19:54 UTC, zimmy87 approved these changes

2020-12-16 20:00 UTC, merged

2020-12-16 20:50 UTC, rajat2004 reviewed
A bit late now, just pointing it out so that it doesn't get forgotten, maybe will add it in a new PR (along with some doc updates)

2020-12-16 20:50 UTC, rajat2004 commented on PythonClient/airsim/client.py
> +            x, y, z (float): Size of each voxel grid dimension in m
Should be `int`, not `float`, from the method arguments defined in C++

2021-03-08 04:56 UTC, GuangyaoSHI commented
> ### About
> 
> This PR introduces a feature that constructs ground truth voxel grids of the world directly from Unreal Engine. The voxel grids are stored in a [binvox format](https://www.patrickmin.com/binvox/binvox.html) which can then be converted by the user into an octomap .bt or any other relevant, desired format. Subsequently, these voxel grids/octomaps can be used within mapping/planning.
> 
> The logic for constructing the voxel grid is in WorldSimApi.cpp->createVoxelGrid(). For now, the assumption is that the voxel grid is a cube - and the API call is:
> 
> ```
> createVoxelGrid(self, position, x, y, z, res, of)
> 
> position (Vector3r): Global position around which voxel grid is centered in m
> x, y, z (float): Size of each voxel grid dimension in m
> res (float): Resolution of voxel grid in m
> of (str): Name of output file to save voxel grid as
> ```
> 
> ### How Has This Been Tested?
> 
> Simple test script:
> 
> ```
> import airsim
> c = airsim.VehicleClient()
> center = a.Vector3r(0, 0, 0)
> c.createVoxelGrid(center, 100, 100, 100, 0.5, "map.binvox")
> ```
> 
> [viewvox](https://www.patrickmin.com/viewvox/) is a nifty little utility to then visualize the created binvox file. Similarly, `binvox2bt` can convert the binvox to an octomap file.
> ### Example voxel grid in Blocks:
> 
> ![image](https://user-images.githubusercontent.com/2274262/101970694-c7755280-3be0-11eb-886c-74f05c839478.png)

Thank you for your work. I went over the C++ code. I think here x, y, z are not the the size of one voxel but the overall size of all voxels because I notice that you use x/res to compute number of cells.

2021-03-09 01:19 UTC, zhudelong commented
Very nice work! Can the voxel grid also model the objects that do not have an entity inside the world model, e.g., leaves?

2021-05-19 15:08 UTC, Leon-Redfield commented
Hi! I'm trying to get the global map in the format of PointCloud, and I tried to use this api simcreatevoxelGrid() but it seems that it doesn't work well for irregular objects such as trees with leaves. Is there any api or plan to add an api which models the whole part of the objects?

2022-10-09 08:15 UTC, Anonymous-N commented
hi! if there is anyway to get the semangtic of voxel?

2022-10-09 08:17 UTC, Anonymous-N commented
hi! Is there any way to get the semantic information of a voxel？thank you

2023-06-02 04:24 UTC, kingchou007 commented
I was wondering how can I get the position of the block.

2023-06-02 04:28 UTC, kingchou007 commented
> I was wondering how can I get the position of the block.

such as the position information of obstacles(x, y)