Add support for fixed external cameras
microsoft/AirSim pull request #3320
Opened 2021-01-19 15:49 UTC by rajat2004

Fixes: 
- #1896
- #1709    

## About

This PR adds the capability to create a fixed camera separate from the cameras on the vehicle, such as a CCTV camera. I'm not aware of any simple way to go about doing this currently, and therefore thought to try it out. I haven't checked the issues very thoroughly, so please let me know if there are other related issues and ways to go about doing this.

This is very much a draft PR, with just the basic implementation done, and not even the Image APIs been implemented apart from the `getCameraInfo` one for sanity check. PR has been opened to get ideas and suggestions and whether this is actually required. This will likely become a big PR, so it can be split into parts for easier review also.

Currently have added a boolean field `external` in the `getCameraInfo` API, but could possible make it a separate API itself, but that'll likely get messy due to many APIs if this PR proceeds.

TODO -
- [ ] Camera APIs implementation
  - [ ] `getImages`
  - [ ] `set/getDistortionParams`
  - [x] `getCameraInfo`
  - [ ] `setCameraFov
  - [ ] `setCameraPose`
- [ ] Allow External Cameras in Subwindows, Recording
- [ ] Unity fixes to preserve earlier behaviour, if possible implement external camera

## How Has This Been Tested?

Draft PR, only `getCameraInfo` has been implemented and tested so far. Example Settings -

```json
{
    "SettingsVersion": 1.2,
    "SimMode": "ComputerVision",
    "ExternalCameras": {
        "fixed1": {
            "CaptureSettings": [
                {
                  "ImageType": 0,
                  "Width": 256,
                  "Height": 144,
                  "FOV_Degrees": 90,
                  "AutoExposureSpeed": 100,
                  "AutoExposureBias": 0,
                  "AutoExposureMaxBrightness": 0.64,
                  "AutoExposureMinBrightness": 0.03,
                  "MotionBlurAmount": 0,
                  "TargetGamma": 1.0,
                  "ProjectionMode": "",
                  "OrthoWidth": 5.12
                }
            ],
            "NoiseSettings": [
              {
                "Enabled": false,
                "ImageType": 0,

                "RandContrib": 0.2,
                "RandSpeed": 100000.0,
                "RandSize": 500.0,
                "RandDensity": 2,

                "HorzWaveContrib":0.03,
                "HorzWaveStrength": 0.08,
                "HorzWaveVertSize": 1.0,
                "HorzWaveScreenSize": 1.0,

                "HorzNoiseLinesContrib": 1.0,
                "HorzNoiseLinesDensityY": 0.01,
                "HorzNoiseLinesDensityXY": 0.5,

                "HorzDistortionContrib": 1.0,
                "HorzDistortionStrength": 0.002
              }
            ],
            "X": 0, "Y": 0, "Z": 0,
            "Pitch": 0, "Roll": 0, "Yaw": 0
        }
    }
}
```

API Call -

```python
client.simGetCameraInfo("fixed1", external=True)
```

## Screenshots (if appropriate):

Will be added later

2021-06-04 05:06 UTC, zimmy87 commented
It seems that you have a lot of conflicts. This is most likely due to conflicts with autoformatted code in master. Please follow these steps to resolve this:

1. check out your pull request
2. run `git checkout master .clang-format` in your repo's root folder
3. if you don't have npm installed, download it from https://www.npmjs.com/get-npm
4. run `npm install -g clang-format`
5. run `clang-format -i path/to/file` for each conflicting file
6. run `git add -u` to track all style changes
7. run `git commit -am "apply style from clang-format"`
8. run `git merge master`
9. resolve other non-style conflicts if you have any
10. push changes

Thanks for helping us with these style changes!

2021-06-04 18:18 UTC, rajat2004 commented
@zimmy87 Yeah, there are _major_ conflicts with this one, will be a pretty painful one. I'll try to get this done today, but I think it would be best to get #3472 in first since that API will also need to be adapted. This PR was just intended to see if the feature is feasible and useful. Any review regarding the code and the current API modification would be very much appreciated!

2021-07-01 16:41 UTC, zimmy87 requested changes
a few comments, plus I'm having an issue running the external_camera.py script

2021-07-01 16:41 UTC, zimmy87 commented on PythonClient/computer_vision/external_camera.py
> +import airsim
can we add `import setup_path` here as an added convenience?

2021-07-01 16:41 UTC, zimmy87 commented on PythonClient/computer_vision/external_camera.py
> +cam_info = client.simGetCameraInfo(CAM_NAME, external=IS_EXTERNAL_CAM)
When I run this script locally with the example settings above, simmode_->getCamera(camera_details) inside WorldSimApi::getCameraInfo() returns a nullptr which results in a read access violation

2021-07-01 18:56 UTC, rajat2004 commented on AirLib/include/api/WorldSimApiBase.hpp
> +                                              const std::string& vehicle_name = "", bool external = false) const = 0;
Changed to use `CameraDetails` struct. Thanks for pointing this out, on changing this code, noticed that I wasn't passing the `vehicle_name`, `external` field to the `getImages` method, fixed this as well.

2021-07-01 18:56 UTC, rajat2004 commented on PythonClient/computer_vision/external_camera.py
> +import airsim
Done

2021-07-01 18:58 UTC, rajat2004 commented on PythonClient/computer_vision/external_camera.py
> +cam_info = client.simGetCameraInfo(CAM_NAME, external=IS_EXTERNAL_CAM)
Fixed this, the problem was in AirSimSettings.hpp where the method to parse the `ExternalCameras` section was not called, probably got removed in fixing the formatting conflicts

2021-07-01 19:01 UTC, rajat2004 commented
I skipped testing this earlier since I generally keep my GPU disabled, and launching UE4 Editor often causes my laptop to give up. Using the subwindow settings in the description -

![Screenshot from 2021-07-02 00-16-28](https://user-images.githubusercontent.com/37938604/124176579-b0d71000-dacc-11eb-9451-55d4a42fd75d.png)

2021-07-12 08:00 UTC, alonfaraj commented
@rajat2004 great feature! thank you for the great work.
Do you think it's worth adding a method to get all the external cameras in the scene?
Similar to `listVehicles`?

2021-07-12 15:55 UTC, rajat2004 commented
Hmm, don't have any real preference either way, pretty straightforward to add that API. The listVehicles API itself becomes more useful with the addVehicle API.

2021-07-14 21:22 UTC, alonfaraj commented
Btw, if you already mentioned it, IMO it might be useful to be able to add external camera in runtime via API.

Just a suggestion :)

2021-07-15 03:33 UTC, rajat2004 commented
Adding external cameras (maybe even normal cameras attached to vehicle) is interesting, and should be possible, though I can't see many usecases for this tbh. Something for a future PR, this one is big enough already :)

2021-07-21 18:19 UTC, zimmy87 requested changes
Mostly just some typos in the docs/comments. I tested this PR locally with the external_camera.py, hello_car.py, detection.py, and hello_drone.py scripts, modified locally for both internal and external cameras. Every call to an impacted API appears to work as expected for both types of cameras. Also ran Unity build and it confirmed it succeeded. This PR looks good to me from a functionality perspective.

2021-07-21 18:19 UTC, zimmy87 commented on docs/settings.md
> +* `CameraName` is any [available camera](image_apis.md#available_cameras) on the vehicle.
`image_apis.md#available_cameras` should be `image_apis.md#available-cameras`

2021-07-21 18:19 UTC, zimmy87 commented on docs/settings.md
> +* `ImageType` integer value determines what kind of image gets shown according to [ImageType enum](image_apis.md#available-imagetype).
`image_apis.md#available-imagetype` should be `image_apis.md#available-imagetype-values`

2021-07-21 18:19 UTC, zimmy87 commented on docs/settings.md
> +* `VehicleName` string allows you to specify the vehicle to use the camera from, used when multiple vehicles are specified in the settings. First vehicle's camera will be used if there are any mistak
some of these bullet points have a colon after the name of the property and some do not; I think we should make this consistent one way or the other (most other bullet points in this doc use a colon, so that's probably preferable here)

2021-07-24 02:35 UTC, rajat2004 commented on PythonClient/computer_vision/external_camera.py
> +A simple script to test all the camera APIs. Change the cmaera name and whether it's an external camera
Fixed

2021-07-24 02:37 UTC, rajat2004 commented on docs/settings.md
> +* `CameraName` is any [available camera](image_apis.md#available_cameras) on the vehicle.
Fixed

2021-07-24 02:38 UTC, rajat2004 commented on docs/settings.md
> +* `ImageType` integer value determines what kind of image gets shown according to [ImageType enum](image_apis.md#available-imagetype).
Fixed

2021-07-24 02:38 UTC, rajat2004 commented on docs/settings.md
> +* `VehicleName` string allows you to specify the vehicle to use the camera from, used when multiple vehicles are specified in the settings. First vehicle's camera will be used if there are any mistak
Done

2021-07-26 17:35 UTC, zimmy87 approved these changes

2021-07-26 17:36 UTC, zimmy87 commented
PR looks good to me; moving ahead with merging

2021-07-26 17:36 UTC, merged