fix broken links in website docs
microsoft/AirSim pull request #3601
Opened 2021-04-15 21:13 UTC by lovettchris

Fixes: #    
lots of broken links found with a webcrawler tool.

## About
Fixing broken links.
This is extracted from the much bigger PR# 3546 so I can break that PR into easier to review parts.

## How Has This Been Tested?
mkdocs build and the webcrawler tool.

## Screenshots (if appropriate):

2021-04-19 23:16 UTC, zimmy87 requested changes
Looks good for the most part, but I think a few links are wrong and some confusing text elsewhere.

2021-04-19 23:16 UTC, zimmy87 commented on docs/px4_sitl.md
> +xbox gamepad. See [remote controllers](remote_control.md#RC_Setup_for_PX4)
I think the right link for this page is: remote_control.md#rc-setup-for-px4

2021-04-19 23:16 UTC, zimmy87 commented on docs/unreal_upgrade.md
> +3. Follow step 1 and 2 to [install Unreal Engine 4.24](build_linux.md#install-and-build).
I don't see any #install-and-build section in build_linux.md, does that part of the link still need to be there?

2021-04-19 23:28 UTC, lovettchris commented on docs/px4_setup.md
> +The "Barometer" setting keeps PX4 happy because the default AirSim barometer has a bit too much
Ah, yes, this part is waiting on my other PR "mavlinkfixes"... I'll remove this sentence until that PR is in.

2021-04-19 23:28 UTC, lovettchris commented on docs/px4_sitl.md
> +    "Barometer" setting keeps PX4 happy because the default AirSim barometer has a bit too much
Fixed

2021-04-19 23:31 UTC, lovettchris commented on docs/px4_sitl.md
> +xbox gamepad. See [remote controllers](remote_control.md#RC_Setup_for_PX4)
yes indeed, thanks for catching this!

2021-04-19 23:32 UTC, lovettchris commented on docs/unreal_upgrade.md
> +3. Follow step 1 and 2 to [install Unreal Engine 4.24](build_linux.md#install-and-build).
Yep, good catch, I'll remove the fragment.

2021-04-19 23:33 UTC, lovettchris commented on docs/log_viewer.md
> +installer](http://www.lovettsoftware.com/LovettSoftware/Downloads/Px4LogViewer/Px4LogViewer.application).
Thanks for the excellent review, I've fixed all the issues you found.

2021-04-21 03:21 UTC, rajat2004 reviewed
`distance_sensor.md` should be added to the navigation in `mkdocs.yml` so that it appears in the sidebar. `mkdocs build` does give an info message about the missing page, but currently doesn't treat it as a warning

2021-04-21 05:05 UTC, lovettchris commented
@rajat2004, fixed and I added a toc level for "Sensors" to group this content as I expect it will grow over time...
![image](https://user-images.githubusercontent.com/18707114/115499540-74fa1180-a224-11eb-8873-d2631936b887.png)

2021-04-27 17:19 UTC, zimmy87 approved these changes

2021-04-27 17:19 UTC, merged