GazeboDrone project added to connect a gazebo drone to the AirSim drone
microsoft/AirSim pull request #3754
Opened 2021-06-01 19:27 UTC by jonyMarino

Fixes: #    

## About

## How Has This Been Tested?

## Screenshots (if appropriate):

2021-06-03 16:55 UTC, zimmy87 requested changes
looks good other than some minor comments

2021-06-03 16:55 UTC, zimmy87 commented on GazeboDrone/src/main.cpp
> +void cbLocalPose(ConstPosesStampedPtr& _msg)
any reason for the underscore prefix here? same for `cbGobalPose()`

2021-06-03 16:55 UTC, zimmy87 commented on GazeboDrone/src/main.cpp
> +    gazebo::transport::SubscriberPtr subPose2 = node->Subscribe("~/pose/info", cbGobalPose);
locals should have under_scored style

2021-06-03 16:55 UTC, zimmy87 commented on GazeboDrone/src/main.cpp
> +            o.z() = -oz;
You can simplify this by calling constructors for p & o

2021-06-07 14:24 UTC, jonyMarino commented on GazeboDrone/src/main.cpp
> +void cbLocalPose(ConstPosesStampedPtr& _msg)
ready

2021-06-07 14:24 UTC, jonyMarino commented on GazeboDrone/src/main.cpp
> +    gazebo::transport::SubscriberPtr subPose2 = node->Subscribe("~/pose/info", cbGobalPose);
ready

2021-06-07 14:24 UTC, jonyMarino commented on GazeboDrone/src/main.cpp
> +            o.z() = -oz;
ready

2021-06-07 15:39 UTC, zimmy87 approved these changes

2021-06-07 15:41 UTC, merged

2021-06-09 21:45 UTC, nkbeebe commented
Is it feasible to replace the gazebo drone for a fixed wing model, to run the physics behind a plane, but still use AirSim for the data collection?

2021-06-10 16:32 UTC, jonyMarino commented
@nkbeebe. Yes, you can do that. It would be great if someone contributes with an API method to set the rotors' angular velocity. Take a look at this tutorial on how to change the drone mesh: https://youtu.be/Bp86WiLUC80. You need to get the mesh of the vehicle you are trying to simulate. You would help the community a lot if you post a video on youtube on how to run AirSim with FixedWing in the way you decide to do it. Keep me updated please.

2021-06-10 16:54 UTC, nkbeebe commented
But is that using Gazebo physics of a drone? Akin to simply replacing the Gazebo drone with a plane, but moving the plane as a drone would? My question is more of using the physics engine of a Gazebo plane, alongside the mesh. So the plane moves in the dynamics a Gazebo plane would move - not a gazebo drone would.

2021-06-10 17:17 UTC, jonyMarino commented
Yes, I have understood your question. I'm not 100% sure if it is going to work, I think so. The GazeboDrone project subscribes to the pose updates of the drone and sends them to the AirSim drone through setVehiclePose, so if you use a plane in gazebo and the GazeboDrone project, can subscribe to its pose, then it will work.

2021-06-13 15:31 UTC, nikitabeebe commented
Sorry if this is a simple question, but following the readme for this merge, I need to have UE4 running with the original AirSim build using clang, then once that is up along with gazebo, I can use the command ./GazeboDrone to then start that simulation? And for the build step, what directory am I creating a new build directory? (In the modified airsim file, replacing the original build folder?)

2021-06-15 19:37 UTC, jonyMarino commented
Hi @nikitabeebe! You are correct about the order.
The build folder goes inside the GazeboDrone folder.

2021-07-12 19:14 UTC, nikitabeebe commented
Also, does this project require the use of PX4, or can it be run without that program entirely? (Just using QGroundControl for joystick input)

2021-07-12 19:47 UTC, jonyMarino commented
Hi @nikitabeebe! I think QGroundControl only works with PX4. But yes, you should be able to connect to gazebo without PX4 connected to it.

2021-07-12 20:50 UTC, nikitabeebe commented
Thank you for confirming. That's what I initially thought @jonyMarino. If you could then, can you take a look at an issue request I created, as I am still unable to compile and run this project like you have demonstrated. I've tried to rule out all the issues with versions or missing dependencies, but I keep getting hung up on the make task for building the GazeboDrone...

https://github.com/microsoft/AirSim/issues/3874

Any input or insight into possible fixes would be a life saver!