Fix bug in UDP socket failing with WSAECONNRESET in the read thread
microsoft/AirSim pull request #3757
Opened 2021-06-04 01:50 UTC by lovettchris

Fixes: #    
issue 3698

## About
Fix bug in UDP socket failing with WSAECONNRESET in the read thread if it tries to read to soon.  The fix is to put a retry count in the UdpClientPort where it automatically reconnects up to 10 times.  Also fixed a null ref crash on mav_vehicle_ that happens in some cases like if you kill px4 process while drone is flying.

## How Has This Been Tested?
Windows with PX4 in WSL2 and in WSL1 with latest PX4 master bits as of today (1.12.0)

## Screenshots (if appropriate):

2021-06-17 16:31 UTC, zimmy87 requested changes
Just a few typos. I did some regression testing with connecting to PX4 & running the hello_drone.py, box.py, and a custom script sending the drone in a zig-zag pattern. Didn't notice any regressions with this testing.

Also tested each of the linked issues with and without this PR applied and found the following:
| issue | w/o PR applied                                  | w/ PR applied                                   |
|-------|-------------------------------------------------|-------------------------------------------------|
| #3698 | repros (AirSim hang on quit after PX4 shutdown) | repros (AirSim hang on quit after PX4 shutdown) |
| #2924 | no repro (w/ PX4 on both WSL2 & cygwin)         | no repro                                        |
| #2112 | repros                                          | no repro                                        |
| #634  | repros (dupe of #2112)                          | no repro (dupe of #2112)                        |
| #1516 | no repro                                        | no repro                                        |

During testing, I encountered a delay in the PX4 connection process where the console outputs `not receiving any messages from HIL, please restart your HIL node and try again`:

![Screenshot from 2021-06-16 09-55-27](https://user-images.githubusercontent.com/5205889/122436390-a30e8000-cf4d-11eb-8225-5a7ed4f9e380.png)

This issue didn't persist for me and went away after restarting my system, so I can't confirm whether it's due to this PR or not, but I wanted to bring it up here in case you had some insight.

2021-06-17 16:31 UTC, zimmy87 commented on MavLinkCom/src/serial_com/UdpClientPort.cpp
> +        int localPort = 0;
locals should be under_scored

2021-06-17 16:31 UTC, zimmy87 commented on PythonClient/multirotor/opencv_show.py
> +print("Connected: now whiled this script is running, you can open another")
"whiled" should be "while"

2021-06-17 18:30 UTC, lovettchris commented on PythonClient/multirotor/opencv_show.py
> +print("Connected: now whiled this script is running, you can open another")
Fixed

2021-06-17 18:32 UTC, lovettchris commented on MavLinkCom/src/serial_com/UdpClientPort.cpp
> +        int localPort = 0;
fixed

2021-06-18 17:21 UTC, zimmy87 approved these changes

2021-06-18 17:22 UTC, zimmy87 commented
Thanks for the contribution @lovettchris! Going ahead with merge

2021-06-18 17:22 UTC, merged