Enable some warnings
microsoft/AirSim pull request #3945
Opened 2021-08-10 03:42 UTC by rajat2004

Fixes: #    

## About

Enables a few warnings for AirSim and the ROS wrapper, needs testing and fixing the warnings

## How Has This Been Tested?

Compilation only 

## Screenshots (if appropriate):

2021-09-26 11:24 UTC, rajat2004 commented on AirLib/include/common/ImageCaptureBase.hpp
> -            ImageRequest()
This is a breaking change, will require changes in any existing C++ client code if they're using it. Can be added back easily if not preferred

2021-12-04 12:25 UTC, rajat2004 commented on AirLib/include/common/ImageCaptureBase.hpp
> -            ImageRequest()
Change reverted

2021-12-09 11:42 UTC, zimmy87 requested changes
Tested building this locally and everything appears to be working fine, so this looks like a safe change to make, but I have a question about what the expected output of build.cmd should be as well as a few style comments.

2021-12-09 11:42 UTC, zimmy87 commented on cmake/cmake-modules/CommonSetup.cmake
> +                -Wall -Wextra \
Should I be seeing extra warnings in the output of build.cmd due to these added flags? I'm getting the same number of warnings both with and without this PR applied, is that to be expected?

2021-12-09 11:42 UTC, zimmy87 commented on DroneShell/include/SimpleShell.hpp
> +            // ShellCommand() {}
Is there any reason to keep this code commented out?

2021-12-09 11:42 UTC, zimmy87 commented on ros/src/airsim_ros_pkgs/src/pd_position_controller_simple.cpp
> +            // ROS_INFO_STREAM("[PIDPositionController] geodetic_converter_ GPS reference initialized correctly (lat long in radians) " << initial_latitude << ", "<< initial_longitude << ", " << init
Any reason for this commented out code? Also same for ln 230-233

2021-12-10 11:43 UTC, rajat2004 commented on cmake/cmake-modules/CommonSetup.cmake
> +                -Wall -Wextra \
The CMake setup is used only in Linux, not in Windows. I haven't currently looked into enabling more warnings for Windows with Visual Studio

2021-12-11 10:43 UTC, rajat2004 commented on DroneShell/include/SimpleShell.hpp
> +            // ShellCommand() {}
Currently have reverted the change since I'm not very clear why there's a private constructor

2021-12-11 10:44 UTC, rajat2004 commented on ros/src/airsim_ros_pkgs/src/pd_position_controller_simple.cpp
> +            // ROS_INFO_STREAM("[PIDPositionController] geodetic_converter_ GPS reference initialized correctly (lat long in radians) " << initial_latitude << ", "<< initial_longitude << ", " << init
Removed, might have been useful for debugging purposes

2021-12-15 00:55 UTC, zimmy87 commented on cmake/cmake-modules/CommonSetup.cmake
> +                -Wall -Wextra \
my mistake, I got confused about which build scripts were consuming the CMake configuration files; resolving this comment

2021-12-15 00:55 UTC, zimmy87 approved these changes

2021-12-15 00:56 UTC, zimmy87 commented
Tested build.sh and the ros wrapper are still working on Ubuntu 20.04; going to move ahead with merging this.

2021-12-15 00:56 UTC, merged