Dynamically set object textures from existing UE material or texture PNG
microsoft/AirSim pull request #3992
Opened 2021-08-28 02:25 UTC by saihv

### About

This PR adds API functions to dynamically change the textures of in-game objects either to existing Unreal material assets (`simSetObjectMaterial`), or to arbitrary texture PNGs (`simSetObjectMaterialFromTexture`). Path to a `.uasset` or an image file (`.png`, `.jpg` etc.) should be specified based on the function being used.

### How Has This Been Tested?
Run AirSim with the Blocks map, and run `PythonClient/environment/change_texture_example.py`

### Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/2274262/131203308-405bc6b1-1866-4a4c-88ce-0ec35aabefb3.png)

2021-08-28 08:02 UTC, rajat2004 reviewed
Really love the texture in the example!

2021-08-28 08:02 UTC, rajat2004 commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +        UMaterial* material = (UMaterial*)StaticLoadObject(UMaterial::StaticClass(), nullptr, *FString(material_name.c_str()));
Any other way than a C-style cast?

2021-08-28 08:02 UTC, rajat2004 commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +        if (material != nullptr && actor != nullptr) {
IsValid ?

2021-08-28 08:02 UTC, rajat2004 commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +            TArray<UStaticMeshComponent*> c;
Maybe `components` or something else instead of single letter vars

2021-08-28 08:02 UTC, rajat2004 commented on Unreal/Plugins/AirSim/Source/WorldSimApi.cpp
> +    success = true;
Same, always true, incorrect if actor or material is invalid

2021-08-28 23:51 UTC, saihv commented
Thanks for the review, @rajat2004 - I've pushed some fixes!

2021-11-04 09:07 UTC, zimmy87 requested changes
Hi @saihv, thanks for submitting this PR, this looks like a good change to take, however I'm having trouble launching the Blocks environment with your PR checked out. I get the following error message:

```
---------------------------
Message
---------------------------
Default Property warnings and errors:
Error: CDO Constructor (SimModeBase): Failed to find Material'/AirSim/HUDAssets/DomainRandomizationMaterial.DomainRandomizationMaterial'


---------------------------
OK   
---------------------------
```

I checked and confirmed that Unreal/Plugins/AirSim/Content/HUDAssets/DomainRandomizationMaterial.uasset is present in my repo and Blocks environment, but it doesn't show up in the editor. Just out of curiosity, which version of the editor are you using? There may be a version mismatch here.

2021-11-09 08:51 UTC, zimmy87 approved these changes

2021-11-09 08:53 UTC, zimmy87 commented
I was able to test this locally and confirmed the new APIs are working as expected. Thanks for submitting this PR @saihv!

2021-11-09 08:53 UTC, merged