Fix trace toggling for multiple vehicles
microsoft/AirSim pull request #4266
Opened 2022-01-04 02:12 UTC by rajat2004

Fixes: #4260     

## About

Now tracing gets enabled for all the vehicles 
TODO: Cleanup of SimHUD code

## How Has This Been Tested?

Using the `Pythonclient/multirotor/multi_agent_drone.py` script and settings
![Screenshot from 2022-01-04 07-34-39](https://user-images.githubusercontent.com/37938604/148000444-796e3df2-91c6-40e0-b219-a30b0fd0786a.png)

## Screenshots (if appropriate):

2022-01-07 03:29 UTC, rajat2004 commented
@zimmy From #4274 looks like a new release is going to happen soon. Is it possible to have this PR included as well?

2022-01-10 11:09 UTC, zimmy87 requested changes
Thanks for fixing this this @rajat2004! Tested locally and this works for me just fine. Left one comment about cleaning up the Unity wrapper. Will talk with the team about whether to include this in the next release.

2022-01-10 11:09 UTC, zimmy87 commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.h
> -    void setSubwindowCameraType(int window_index, ImageType type);
getSubwindowCameraType, getSubwindowCameraType, getSubwindowVisible, and setSubwindowVisible are also defined [here](https://github.com/microsoft/AirSim/blob/master/Unity/AirLibWrapper/AirsimWrapper/Source/SimHUD/SimHUD.cpp#L46). Is there any reason to not clean up the Unity wrapper as well?

2022-01-11 03:01 UTC, rajat2004 commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.h
> -    void setSubwindowCameraType(int window_index, ImageType type);
Main reason was that I currently don't have a working Unity installation, going through that code, none of the subwindow code in Unity SimHUD.cpp seems to be actually used, and the subwindows are created in AirsimHUDScript.cs
Will try to go through it a bit more

2022-01-12 07:06 UTC, zimmy87 commented on Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.h
> -    void setSubwindowCameraType(int window_index, ImageType type);
I have a working Unity installation, so I decided to commit this cleanup change after testing that subwindows still functioned normally in my Unity build. Once I get this merged, I'll include it in the next release.

2022-01-12 08:13 UTC, zimmy87 approved these changes

2022-01-12 08:13 UTC, zimmy87 commented
Thanks for submitting this PR @rajat2004! Moving ahead with merging.

2022-01-12 08:14 UTC, merged

2022-01-12 10:57 UTC, rajat2004 commented
Thanks a lot @zimmy87 for the Unity changes! I'll get my old setup working over the weekend, sorry for this